apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: gateway
  labels:
    description: 'LumiGateway'
spec:
  deviceModelRef:
    name: gateway-model
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: ''
        operator: In
        values:
        - worker01

status:
  twins:
    - propertyName: power
      desired:
        metadata:
          type: string
        value: 'OFF'
      reported:
        metadata:
          type: string
        value: 'OFF'
    - propertyName: brightness
      desired:
        metadata:
          type: string
        value: '50'
      reported:
        metadata:
          type: string
        value: '50'
