apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: yeelight-controller
  name: yeelight-controller-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: yeelight-controller
  template:
    metadata:
      labels:
        k8s-app: yeelight-controller
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      hostNetwork: true
      containers:
      - name: yeelight-controller-container
        image: mistyfalcon/yeelight-controller:v1.1.0
        imagePullPolicy: IfNotPresent
      nodeSelector:
        node-role.kubernetes.io/edge: ""
      restartPolicy: Always
